### PR TITLE
S3 cache rebase

### PR DESCRIPTION
**Pull request by borkaehw**
Hi Greg, I am working with @jjudd at Lucid Software. I am here to help this PR to be merged. I rebased this PR https://github.com/bazelbuild/bazel/pull/4889 from `bazelbuild/master`.

### CODE REVIEW

**Comment by GregBowyer** [comment]
Out of question how did we end up with conflicts here?

**Comment by borkaehw** [comment]
I believe it's because when I did `git rebase master`, git changed the commit itself instead of creating a new commit. So the contents in each commit might be different (to resolve conflicts) and the hashes are different.

**Comment by GregBowyer** [comment]
I am tagging the old code in case, but I am going to take you on your word here

**Comment by GregBowyer** [comment]
Thanks for the rebase

**Pull request merged**
